// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using firsttask.Data;

#nullable disable

namespace firsttask.Migrations
{
    [DbContext(typeof(MyFirstContext))]
    partial class MyFirstContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("firsttask.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "لباس"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "شلوار"
                        });
                });

            modelBuilder.Entity("firsttask.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "seed data1",
                            ProductName = "پیراهن مردانه",
                            ProductPrice = 5000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "seed data2",
                            ProductName = "لی",
                            ProductPrice = 1000.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "seed data1",
                            ProductName = "پیراهن زنانه",
                            ProductPrice = 5000.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "seed data2",
                            ProductName = "کتان",
                            ProductPrice = 1000.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            Description = "seed data1",
                            ProductName = "هودی",
                            ProductPrice = 5000.0
                        });
                });

            modelBuilder.Entity("firsttask.Models.Product", b =>
                {
                    b.HasOne("firsttask.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("firsttask.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
